---
- hosts: all
  become: true
  become_user: root
  tasks:
   - name: Copy the file owned by azureuser using root and assign new owner as a user(haroldgm)
     copy:
       src: /tmp/file_of_azureuser
       dest: /tmp
       owner: haroldgm
       group: root
       mode: 0777
     when: ansible_hostname == "Remote1"
