---
- hosts: dev
  become: true
  become_user: root
  tasks:
    - name: Restart Remote1 SLES system
      command: shutdown -r
      when: ansible_os_family == "Suse" and  ansible_hostname == "Remote1" and ansible_distribution_major_version == "15" and ansible_kernel == "5.3.18-150300.38.88-azure"
    # Alternatively, you can use this multiline AND condition
    # when:
    #   - ansible_os_family == "Suse"
    #   - ansible_hostname == "Remote1"
    #   - ansible_distribution_major_version == "15"
    #   - ansible_kernel == "5.3.18-150300.38.88-azure"
