---
- hosts: "{{target_hosts}}"
  become: true
  become_user: root
  tasks:
    - name: Update package cache for SUSE
      when: ansible_distribution == 'openSUSE Leap'
      zypper:
        update_cache: yes
        name: '*'
        state: latest

    - name: Update package cache for RHEL
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
      yum:
        update_cache: yes
        name: '*'
        state: latest


    - name: Install available updates for SUSE
      when: ansible_distribution == 'openSUSE Leap'
      zypper:
        name: '*'
        state: latest

    - name: Install available updates for RHEL
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
      yum:
        name: '*'
        state: latest


    - name: Reboot server
      reboot:

    - name: Wait for server to boot up
      wait_for:
        host: "{{item}}"
        port: 22
        delay: 10
        timeout: 60
        state: started
      ignore_errors: true
      loop: "{{ groups['target_hosts'] }}"

    - name: Check server status
      shell: hostnamectl
      register: server_status

    - name: Print server status
      debug:
        var: server_status.stdout_lines
