---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Update package cache
      zypper:
        update_cache: yes
        name: '*'
        state: latest

    - name: Reboot server
      reboot:

    - name: Wait for server to boot up
      wait_for:
        host: "Remote1"
        port: 22
        delay: 10
        timeout: 300
        state: started

    - name: Check server status
      shell: hostnamectl
      register: server_status

    - name: Print server status
      debug:
        var: server_status.stdout_lines
