---
- hosts: all
  become: true
  become_user: root
  tasks:
   - name: Copy the file owned by azureuser using root and assign new owner as a user(haroldgm)
     copy:
       src: ../03_scripts
       dest: /tmp
       owner: haroldgm
       group: root
       mode: 0777

   - name: Install python virtual environment
     script: /tmp/03_scripts/02_update_password.sh    
