---
- hosts: all
  become: true
  become_user: root
  tasks:
   - name: Copy the scripts to remote clients
     copy:
       src: ../03_scripts
       dest: /tmp
       owner: root
       group: root
       mode: 0777

   - name: User password update
     shell: |
       cd /tmp/03_scripts/
       ./02_update_passwd.sh
     register: script_result
     failed_when: script_result.rc != 0

   - name: Display results of user password update  
     debug:
       var: script_result.stdout_lines

   - name: User login Test
     shell: |
       cd /tmp/03_scripts/
       ./03_verify_passwd.sh
     register: script_result2
     failed_when: script_result2.rc != 0

   - name: Display results of user login test
     debug:
       var: script_result2.stdout_lines

