---
- hosts: dev
  become: true
  become_user: root
  vars:
    web_pkg: nginx
    database_pkg: mysql
  tasks:
    - name: Install Nginx and Mysql
      zypper:
            name: 
                - "{{ web_pkg }}"
                - "{{ database_pkg }}"
            state: present
    
    - name: Activate Nginx
      service:
             name: "{{ web_pkg }}"
             state: started

    - name: Activate mysql
      service:
             name: "{{ database_pkg }}"
             state: started
    
    - name: Install python-pip
      zypper:
            name: python-pip
            state: present

    - name: Install python virtual environment
      shell: |
           pip install virtualenv
           virtualenv name-env
           pip install django

    - name: Copy a file from controller to remote
      copy:
          src: /tmp/file_from_root.txt
          dest: /tmp/file_from_root.txt
